# Numpy exercices pratiques
Ce notebook à pour objectif de vous faire pratiquer numpy dans toute sa généralité. 
Vous avez donc une liste de questions à faire ! Il ne faut pas hésiter à faire des recherches sur google ainsi que voir la [documentation officielle](https://docs.scipy.org/doc/numpy-1.13.0/reference/). 

#### Q1 : Importer le package numpy 

In [4]:
import numpy as np

#### Q2 : Afficher la version de numpy et la configuration 

In [9]:
np.show_config()
np.version.version

blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]


'1.19.2'

#### Q3 : Créer un vecteur nul de taille 10

In [10]:
nul=np.zeros(10);nul

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Q4 : Créer un vecteur null de taille 10 et affecter la valeur 1 à la 4ème place (index 4) du vecteur

In [14]:
null=np.zeros(10)
null[4]=1;null

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### Q5 : Créer un vecteur Z de 40 valeurs allant de 10 à 50 

In [16]:
Z=np.arange(10,51);Z

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### Q6 : Inverser Z (le premier élément devient donc le dernier)

In [67]:
np.flip(Z)

array([50, 49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34,
       33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17,
       16, 15, 14, 13, 12, 11, 10])

#### Q7 : Créer une matrice 3x3 avec des valeurs comprise entre 0 et 8 

In [19]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Q8 : Créer une matrice identié 3x3 

In [47]:
np.diag(np.ones((3)))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Q9 : Créer une matrice 3x3x3 avec des valeurs random 

In [66]:
np.random.rand(3,3,3) #aléatoire entre [0,1)

array([[[0.74549005, 0.807986  , 0.0328965 ],
        [0.22794467, 0.72732073, 0.0855637 ],
        [0.4067704 , 0.85939981, 0.04608265]],

       [[0.25404342, 0.82321568, 0.67553298],
        [0.64822174, 0.18212855, 0.23093388],
        [0.44261198, 0.37223656, 0.26181861]],

       [[0.42518021, 0.71806612, 0.33259678],
        [0.20818418, 0.4450873 , 0.27384396],
        [0.04590665, 0.25369318, 0.34232675]]])

#### Q10 : Créer une matrice 10x10 avec des valeurs random et afficher le minimum et maximum de cette matrice

In [37]:
M=np.random.rand(10,10)
print("min=",M.min(),"max=",M.max())

min= 0.013598287181739721 max= 0.9931509230728449


#### Q11 : Créer une matrice 5x5 avec les valeurs 1,2,3,4 en dessous de la diagonale 

In [46]:
np.diag([1,2,3,4],-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### Q12 : Créer une liste random de taille 5 et donner la somme de ses éléments  

In [56]:
random=np.random.rand(5); random.sum() #aléatoire entre [0,1)

2.344755136696027

#### Q13 : Créer une liste random de taille 5 et donner la moyenne de ses éléments

In [48]:
random=np.random.rand(5); random.mean() #aléatoire entre [0,1)

0.6685372664895789

#### Q14 : En utilisant une fonction, donner la taille de la liste suivante :
```python 
l = [x for x in range(11)]
```

In [72]:
l = [x for x in range(11)]
np.array(l).size

11

#### Q15 : Créer un tableau de taille 10 avec des valeurs comprises entre 0 et 1 EXCLUS 

In [73]:
np.random.rand(10)

array([0.67180544, 0.23141661, 0.56627629, 0.38319693, 0.16936736,
       0.71444792, 0.76702844, 0.18713426, 0.41653228, 0.06898703])

#### Q16 : Soit deux tableau A et B de dimension 1 et de taille 5, créer A et B et afficher True si A et B sont égaux False sinon

In [75]:
A,B=np.random.rand(5),np.random.rand(5)
(A==B).all() #Si les tableaux sont égaux

False

#### Q17 : Convertir un tableau de float32 de dimension 1 et de taille 10 en un tableau de meme taille et dimension mais de type int32

In [102]:
np.arange(10, dtype='float32').astype('int32')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### Q18 : Normaliser une matrice random 5x5 
La normalisation d'un nombre X consiste à lui retirer sa moyenne et a diviser le tout par son écart type 

In [110]:
n=np.random.rand(5,5)
(n-n.mean())/n.std()

array([[ 0.09171792,  0.99526019, -1.25482772,  1.55217382, -1.63621449],
       [ 0.57573628, -0.67497397,  1.42268013,  1.28045345,  0.98415939],
       [-0.56413491, -1.43349684,  0.81540705, -0.87214684,  1.21235906],
       [-1.31986323, -0.39052685, -0.74160233,  0.3195933 , -0.20764732],
       [ 0.66138878, -1.19820141, -0.9209435 ,  0.15609179,  1.14755825]])

#### Q19 : Créer une matrice random `M` 2x2 et donner sa transposer 
L'opération de transposition dans une matrice consiste à échanger les lignes et le colonnes. 

In [109]:
np.random.rand(2,2).transpose()

array([[0.30805059, 0.72001646],
       [0.56142616, 0.34739944]])

#### Q20 : Écrire un petit script qui remplace un élément au hasard dans une matrice de dimension NxN

#### Q21 : Considérons une matrice de dimension (5,5,3), écrire un script qui multiplie cette matrice par une matrice de dimension (5,5)